version: "3.7"

services:
  chat-service1:
    image: michaelkoconnor/chatty-cathy-chat-service
    container_name: chat-service1
    build: ./chat-service
    depends_on:
      - redis
      - db
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    env_file: ./chat-service/.env
    # networks:
    #   - dev-network

  chat-service2:
    image: michaelkoconnor/chatty-cathy-chat-service
    container_name: chat-service2
    build: ./chat-service
    depends_on:
      - redis
      - db
    environment:
      NODE_ENV: development
    ports:
      - 4001:4000
    env_file: ./chat-service/.env
    # networks:
    #   - dev-network

  frontend1:
    image: michaelkoconnor/chatty-cathy-frontend
    container_name: frontend1
    build: ./frontend
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    # networks:
    #   - dev-network

  reverse-proxy:
    image: michaelkoconnor/chatty-cathy-reverse-proxy
    container_name: reverse-proxy
    build: ./reverse-proxy
    depends_on:
      - chat-service1
      - chat-service2
      - frontend1
    ports:
      - 80:80
    # networks:
    #   - dev-network

  redis:
    image: redis
    container_name: cache
    ports:
      - 6379:6379
    # networks:
    #   - dev-network

  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: chattycathy
      POSTGRES_HOST: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    # networks:
    #   - dev-network

  seed-db:
    image: michaelkoconnor/chatty-cathy-chat-service
    container_name: seed-db
    build: ./chat-service
    command: npm run knex-remake
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    env_file: ./chat-service/.env
    # networks:
    #   - dev-network

  test:
    image: michaelkoconnor/chatty-cathy
    build: ./chat-service
    environment:
      NODE_ENV: test
    command: npm test
    ports:
      - 4000:4000
    env_file: ./chat-service/.env
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
