version: "3.7"

services:
  chatty-cathy:
    image: michaelkoconnor/chatty-cathy
    build: .
    depends_on:
      - redis
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
    env_file: .env
    networks:
      - dev-network

  chatty-cathy1:
    image: michaelkoconnor/chatty-cathy
    build: .
    depends_on:
      - redis
    environment:
      NODE_ENV: production
    ports:
      - 4001:4000
    env_file: .env
    networks:
      - dev-network

  reverse-proxy:
    image: michaelkoconnor/chatty-cathy-nginx
    container_name: reverse-proxy
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - dev-network

  redis:
    image: redis
    container_name: cache
    ports:
      - 6379:6379
    networks:
      - dev-network

  test:
    image: michaelkoconnor/chatty-cathy
    build: .
    environment:
      NODE_ENV: test
    command: npm test
    ports:
      - 4000:4000
    env_file: .env

networks:
  dev-network:
    driver: bridge
