version: "3.7"

services:
  chat-service1:
    image: michaelkoconnor/chatty-cathy
    build: ./chat-service
    depends_on:
      - redis
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
    env_file: ./chat-service/.env
    networks:
      - dev-network

  chat-service2:
    image: michaelkoconnor/chatty-cathy
    build: ./chat-service
    depends_on:
      - redis
    environment:
      NODE_ENV: production
    ports:
      - 4001:4000
    env_file: ./chat-service/.env
    networks:
      - dev-network

  reverse-proxy:
    image: michaelkoconnor/chatty-cathy-reverse-proxy
    container_name: reverse-proxy
    build: ./nginx
    depends_on:
      - chat-service1
      - chat-service2
    ports:
      - 80:80
    networks:
      - dev-network

  redis:
    image: redis
    container_name: cache
    ports:
      - 6379:6379
    networks:
      - dev-network

  # test:
  #   image: michaelkoconnor/chatty-cathy
  #   build: ./chat-service
  #   environment:
  #     NODE_ENV: test
  #   command: npm test
  #   ports:
  #     - 4000:4000
  #   env_file: ./chat-service/.env

networks:
  dev-network:
    driver: bridge
